### ISSUE TITLE
How to train this model ?

### ISSUE THREAD

**Issue by deep-learning-newbie** [dsbyprateekg/YOLOv4#1]
Hi there! 
Great work, I like this workbook! I just study Yolo and I'd like to train this model on my own dataset. how can I du this ? which format of tensor I should provide to the model. 
Thanks!

**Comment by danbader88** [comment]
@deep-learning-newbie 
This link can help you to train your custom dataset-
[http://dsbyprateekg.blogspot.com/2020/07/my-solution-to-hackerearths-identify.html](url)
