### ISSUE TITLE
Is this work for yolov4 tiny models?

### ISSUE THREAD

**Issue by parameswararao-13** [dsbyprateekg/YOLOv4#2]
hi @dsbyprateekg 
i have a yolov4 tiny model with 256X64 size. Is it possible to convert this into Tf with your repo?

**Comment by dsbyprateekg** [comment]
@parameswar-ds I guess it will not work for tiny version of YOLOv4. But a good news is that following github repo has solution for tiny YOLO models also-
[https://github.com/hunglc007/tensorflow-yolov4-tflite](url)
